name: The Kop Bot Runner

on:
  schedule:
    - cron: '17,47 * * * *' # Run at xx:17 and xx:47 to avoid Github Actions congestion delays
  repository_dispatch:
    types: [run-news, refresh-token]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Determine Command
        id: cmd
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "command=--scheduled-news" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.action }}" == "refresh-token" ]; then
            echo "command=--refresh-token" >> $GITHUB_OUTPUT
          else
            echo "command=--news" >> $GITHUB_OUTPUT
          fi

      - name: Run Bot
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        run: npm run bot -- ${{ steps.cmd.outputs.command }}
